src/main.js, src/modules/interactuadores/interactuadores.js, src/store.js
Se implementó la lógica del yoke. Si se presiona cualquiera de las teclas W,A,S,D, el yoke cambia su estado. Si el yoke no tiene movimiento alguno, su estado será igual a 0. Si se presiona la tecla “W”, el estado del yoke en el pitch cambiará a 1 (elevarse). Por el contrario, si se presiona la tecla “S” el estado del yoke en el pitch cambiará a -1 (descender) .
Si se presiona la tecla “A”, el estado del yoke en el roll cambiará a -1 (izquierda). Por el contrario, si se presiona la tecla “D” el estado del yoke en el roll cambiará a -1 (derecha).
=> feat: implementacion logica yoke

src/main.js, src/modules/interactuadores/interactuadores.js, src/store.js
Creación de controlador para los pedales.
Al apretar la letra "q" por un tiempo, el pedal izquierdo incrementará exponencialmente aumentando su valor de 1 en 1
Al apretar la letra "e" por un tiempo, el pedal derecho incrementará exponencialmente aumentando su valor de 1 en 1
Al dejar de apretar cualquiera de estas teclas por un segundo, estas volverán a su valor inicial (en este caso sería 0).
=> Sprint1 equipo diego gustavo sanchez

src/main.js, src/modules/indicadores/indicadores.js, src/modules/interactuadores/interactuadores.js, src/store.js
[Logre hacer que los valores del heading indicator se muestren por pantalla junto con los valores de los rudder pedals, haciendo que mientras se sigan presionando los valores del indicador se van aumentando y almacenando hasta un maximo de 360, luego se resetea y se vuelve a aumentar.
=> Sprint1 equipo diego miguel eberhard

src/components/MiLuz.vue, src/components/MiPanel.vue, src/main.js, src/modules/indicadores/horizonteArtificial.js, src/modules/indicadores/indicadores.js, src/modules/interactuadores/interactuadores.js, src/store.js
Avances del team Diego de la semana 1. 
Contiene lo siguiente:
-logica yoke
-logica rudder pedals
-logica throttle
-logica tachometer
-logica heading indicator
-logica artificial horizon
=> Sprint1 equipo diego

src/components/tablero/rightHandPanel/FlightHourRecorder.vue, src/components/tablero/rightHandPanel/RightHandPanel.vue
Componente FlightHourRecorder Nicolas Iturra - DIego Mancilla
=> feat: flightHourRecorder

src/components/tablero/rightHandPanel/FlightHourRecorder.vue, src/components/tablero/rightHandPanel/RightHandPanel.vue
Component Flight Hour Recorder
=> solicitud integración componente flight hour recorder

src/components/tablero/centerColumn/TrottleKnob.vue, src/components/tablero/rightHandPanel/MiTachometer.vue, src/main.js
se termino la implementacion de las rpm con el acelerador throttle, este se muestra como aumenta las rpm visualmente cuando se aprta la planca del throttle
=> integracion Throttle y tacometro (RPM)

src/components/tablero/mainPanel/VerticalSpeed.vue, src/main.js, src/modules/indicadores/horizonteArtificial.js, src/modules/indicadores/verticalspeedIndicator.js, src/store.js
Se implementó la lógica del vertical speed indicator y se integró al frontend, la velocidad como tal del avión aún no esta definida, por lo que se utiliza el botón "u" para cambiarla, el angulo es tomado desde el horizonte artificial
=> Sprint2 tapia

src/components/tablero/mainPanel/MiArtificialHorizon.vue, src/components/tablero/rightHandPanel/MiTachometer.vue, src/modules/indicadores/tacometro.js
Se conectó el componente MiTachometer.vue con tacometro.js
=> feat:IntegraciónTacometro

package-lock.json, package.json, src/components/miniMapa/MiniMapa.vue
Se actualiza en base a coordenadas
=> feat: mini map

package-lock.json, src/components/tablero/mainPanel/TurnCoordinator.vue, src/main.js, src/modules/indicadores/horizonteArtificial.js, src/modules/interactuadores/yoke.js, src/store.js
Se agregaron los cambios sugeridos
=> Sprint2 eberhard

src/style.css
Se texturizo el interfaz de los paneles en general y se agregaron detalles
=> fix:MejoraFondoInterfaz

src/components/tablero/mainPanel/TurnCoordinator.vue, src/components/tablero/rightHandPanel/MiTachometer.vue, src/components/terreno/MiTerreno.vue, src/components/terreno/frontView.vue, src/modules/indicadores/topView.js, src/modules/interactuadores/yoke.js, src/store.js
vista desde el frente para ver los alerones del avion
=> feat: vista Frente avion

src/components/tablero/centerColumn/MixtureKnob.vue, src/components/tablero/centerColumn/TrimWheel.vue, src/components/tablero/centerColumn/TrottleKnob.vue, src/modules/indicadores/horizonteArtificial.js
Se implementaron cambios para que trimwheel afecte al controlador del horizonte artificial
=> fix: cambia el valor de pitch en horizonteartificial.js

src/App.vue, src/components/tablero/centerColumn/MixtureKnob.vue, src/components/tablero/mainPanel/TurnCoordinator.vue, src/modules/avion.js, src/modules/interactuadores/mixture.js, src/modules/interactuadores/plane.js, src/store.js
filtren por posicion en el console log para no tener tanto problema con demasiado texto
=> Sprint3 migueles

src/components/tablero/mainPanel/CourseDeviationIndicator1.vue, src/components/tablero/mainPanel/CourseDeviationIndicator2.vue, src/components/tablero/mainPanel/MainPanel.vue
Se crea el front end de los componentes course deviation indicator (NAV1 y NAV2). Además se implementa lógica para que la aguja del componente muestre la dirección en que está el punto de destino. La implementación no está completa.
=> Sprint3 martinez

src/App.vue, src/components/tablero/mainPanel/IgnitionSwitch.vue, src/components/tablero/mainPanel/PrimerBoton.vue, src/components/tablero/rightHandPanel/MiAmperimetro.vue, src/components/tablero/rightHandPanel/RightHandPanel.vue, src/store.js, src/style.css
Se crea el boton "primer", "Ignicion switch" y "amperimetro", estos funcionan si los modificamos manualmente, pero no estan unidos (no estan interactuando entre si).  
Para el boton primer solo tiene dos estados (booleano) los cuales serviran para activar el encendido del avion luego de haber sido apretado un par de veces.
Para el switch se crearon cinco estados los cuales son "off", "r", "l", "both" y "start" (originales del avion). de los cuales solo funcionan el "off" que desactiva el motor (apagandolo) y "start" que daria inicio al motor (prendiendolo). pd: se intento hacer mas bonito pero por honor al tiempo se dejo mas funcional que estetico, se puede comprobar su funcionamiento en consola, este imprime al precionar.
Para el Amperimetro se aplico reutilizacion de codigo el cual fue …
=> Sprint3 villaroel - Desarrollar componentes previos para encender el motor

src/components/tablero/centerColumn/MixtureKnob.vue, src/components/tablero/centerColumn/TrimWheel.vue, src/components/tablero/centerColumn/TrottleKnob.vue, src/modules/indicadores/horizonteArtificial.js
Se ajustaron los componentes trimwheel, trottleknob y mixture para que funcionaran mejor, se eliminaron algunas funciones de arrastre y el mouseup ya que generaban errores a la hora que querer ocupar bien el componente.
=> Sprint3 sanchez

src/components/tablero/mainPanel/CourseDeviationIndicator1.vue, src/components/tablero/mainPanel/CourseDeviationIndicator2.vue, src/components/tablero/mainPanel/FuelQuantity.vue, src/components/tablero/mainPanel/MainPanel.vue, src/components/tablero/mainPanel/MiAirSpeedIndicator.vue, src/components/tablero/mainPanel/MiAltimeter.vue, src/components/tablero/mainPanel/MiArtificialHorizon.vue, src/components/tablero/mainPanel/MiHeadingIndicator.vue, src/components/tablero/mainPanel/TurnCoordinator.vue, src/components/tablero/mainPanel/VerticalSpeed.vue, src/components/tablero/rightHandPanel/AdfNeddle.vue, src/components/tablero/rightHandPanel/FlightHourRecorder.vue, src/components/tablero/rightHandPanel/MiAmperimetro.vue, src/components/tablero/rightHandPanel/MiTachometer.vue, src/components/tablero/rightHandPanel/RightHandPanel.vue, src/style.css
Se arreglaron los estilos que provocaban el rompimiento del mainPanel y rightPanel
=> fix: se arreglaron las cosas que se rompieron

package-lock.json, src/App.vue, src/components/tablero/inferiorPanel/MiYoke.vue, src/components/tablero/mainPanel/MiAirSpeedIndicator.vue, src/components/tablero/mainPanel/TurnCoordinator.vue, src/components/tablero/rightHandPanel/MiAmperimetro.vue, src/modules/avion.js, src/modules/indicadores/airSpeedIndicator.js, src/store.js
-corrección de los knots indicados en el airspeed
-funcion de setear valores en el airspeed actualizada
=> fix:airspeed indicator

src/components/tablero/inferiorPanel/MiYoke.vue, src/components/tablero/rightHandPanel/RightHandPanel.vue
Se pidió centrar también los yoke, pero están se están trabajando de un solo componente, por lo que cuándo se mueve uno, se mueve el otro, lo que hace que no queden centrados dentro del espacio que corresponde. Como posible solución era rehacer el yoke y trabajarlos como componentes separados (uno izquierdo y otro derecho) lo que no comencé por que no creía alcanzar a terminarlo antes de hacer el pull request, ya que por motivos  que trabajo durante el día, debía hacerlo hoy.
=> Sprint4 fernandez

src/components/tablero/mainPanel/MiAltimeter.vue, src/components/tablero/mainPanel/VerticalSpeed.vue
Los componentes quedaron funcionando correctamente y esta a la espera de la implementación de los demás componentes que afectan a estos indicadores para poder adaptar la lógica correctamente. Si muevo el yoke hacia arriba el altímetro y  vertical speed aumentan sus valores, si se mantiene en 0 el yoke el altímetro se queda en el ultimo valor y el vertical speed vuelve a 0 y por ultimo cuando muevo el yoke hacia abajo el tanto el vertical speed como el altímetro disminuyen su valor. Trabaje con Nicolas Barahona.
=> Sprint4 cid

src/components/terreno/TopView.vue, src/modules/indicadores/topView.js
Se añadió la hélice en el top view ,cuando el motor se enciende comienza a girar y después de dos segundos gira mas rápido, si se detiene el motor le hélice se detiene pasado los dos segundos . Además se añadió la lógica para los alerones verdes pero debido a que no existe lógica del wing flap se puso un valor cualquiera que parte en 0 , la idea es que cuando la persona encargada termine esa lógica simplemente con los getters obtener el valor y debería funcionar como corresponde ya que todo lo demas esta a la espera de ese valor
=> feat: implementación de hélice top view

src/App.vue, src/components/tablero/mainPanel/MiAirSpeedIndicator.vue, src/components/tablero/mainPanel/MiArtificialHorizon.vue, src/components/terreno/frontView.vue, src/modules/indicadores/airSpeedIndicator.js, src/modules/indicadores/horizonteArtificial.js
airspeed: muestra la velocidad del avion cuando despega
frontView: implementacion de la helice al encender motor- logica complementaria flaps
=> feat: implementacion airspeed-mejora frontView

src/components/tablero/rightHandPanel/adfRadio.vue, src/modules/indicadores/adfRadio.js
puntos desde el 000 al 075 puntos de ciudades reales
=> fix: adf_radio puntos reales

src/components/tablero/centerColumn/CarburetorHeat.vue, src/components/tablero/centerColumn/MixtureKnob.vue, src/components/tablero/centerColumn/TrottleKnob.vue, src/components/tablero/centerColumn/WingFlaps.vue, src/components/tablero/mainPanel/PrimerBoton.vue, src/main.js, src/modules/avion.js, src/modules/interactuadores/mixture.js
Añadi los cambios sugeridos a lo implementado en la semana pasada.
Las perillas ahora se ejecutan unicamente con el mouse y se muestran el valor por pantalla (los numeros ahora son de color blanco)
El boton del primer funciona y se guarda su estado en avion.js
El carburator es el unico que deje funcionando con teclado ("u" e "i")
=> Sprint5 eberhard

src/components/tablero/centerColumn/WingFlaps.vue, src/modules/avion.js
Se agrega la lógica del componente especificada en el diseño lógico para volar a menores velocidades.
Se obtienen las variables globales como velocidad y tambien se setean las mismas para cambiar el valor global.
Tambien se hicieron pequeños cambios visuales.
=> Sprint5 falcon

src/components/tablero/centerColumn/TrimWheel.vue
implementación e integración de la función del trim wheel, se cambia el valor del pitch según el valor obtenido por el componente visual y se mantiene constante hasta que se cambia por medio de las teclas del Yoke o nuevamente desde el componente visual
=> feat: trim-wheel
